### ISSUE TITLE
Concrete and uranium

### ISSUE THREAD

**Issue by Austin5003** [ballgamer56/VanillaExtended#2]
Due to the super fucky way in which resource data is unlocked, concrete won't ever show up in the core database, which makes it impossible to sort

And there's no campaign map or any method of obtaining uranium

**Comment by ballgamer56** [comment]
Yes, There's no map that has uranium and once you unlock the resource (via producing it the first time in any game) you should be able to sort it right away (Tested on steam build 104.6) if that's not your problem, feel free to give me more info about it :)

**Comment by Austin5003** [comment]
I've produced tons of concrete but it's not being unlocked

**Comment by ballgamer56** [comment]
what platform are you using this mod on? The latest update doesn't have this issue as I tested it couples of time
Also. the latest update of this mod now have campaign map for mining uranium

**Comment by Austin5003** [comment]
The core in that zone needs to be set to the yellow team, not they gray team

**Comment by ballgamer56** [comment]
Oh, oops. The fix is coming!

**Comment by Austin5003** [comment]
Do you have a preferred method of contact so I can send you map fixes whenever I spot issues?

**Comment by ballgamer56** [comment]
Yes, Discord server
https://discord.gg/NX6rBDU

**Comment by Bassem-Const** [comment]
> Owner

Thanks!

**Comment by The4codeblocks** [comment]
> Yes, Discord server https://discord.gg/NX6rBDU

Thanks!
