### ISSUE TITLE
Campaign mission won't start

### ISSUE THREAD

**Issue by Martinocom** [ballgamer56/VanillaExtended#3]
I imported the mod from GitHub, version 1.4. All machinery works ok in all maps, but the main mission won't start (no timer, no waves coming). I can build and gather resources, but nothing will happen.

I have a Mi A2, rooted, with Pixel Experience, Android 10. Game version 104.6.

**Comment by ballgamer56** [comment]
it is fixed, sorry for a very very late reply. I'll keep this issue open for now in case anything went wrong about the update

**Comment by Martinocom** [comment]
Seems to work fine. I'll try to get deeper in the waves and I'll see if something will break. For now all right 👍

**Comment by Martinocom** [comment]
It's the campain supposed to have uranium as mineable resoruce? Cos I only noticed now the "uranium ore" disappeared from the map. It is still obtainable via uranium drill.

**Comment by ballgamer56** [comment]
I know this one is over a year ago now, but the campaign system had been tweaked in the V6 update, and the map has been reduced to just a custom game map, and I made an alternative way to get uranium already
