### ISSUE TITLE
Sprite for a block in the mod

### ISSUE THREAD

**Issue by The4codeblocks** [ballgamer56/VanillaExtended#9]
The sprite for the H2Coal doesn't fit into the game, so I made a re-sprite of it
![waterToCoal](https://user-images.githubusercontent.com/72419529/173886862-91355578-2910-4991-9590-229690d02989.png)
.

**Comment by ballgamer56** [comment]
That's pretty good, please put it as pull request so I can merge it

**Comment by The4codeblocks** [comment]
> That's pretty good, please put it as pull request so I can merge it

Done!
